In [1]:
import numpy as np

In [19]:
"""Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde."""

def vandermode(arr,n,increasing):
    if increasing:
        arr_op = np.array([x**i for x in arr for i in range(n)]).reshape(-1,n)
    else:
        arr_op = np.array([x**(n-i-1) for x in arr for i in range(n)]).reshape(-1,n)
    
    return arr_op

arr = np.array([1,2,3,4,5])
n=5
print(vandermode(arr,n,True))
print("*"*30)
print(vandermode(arr,n,False))

[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
******************************
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [44]:
"""Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3."""



def movavg(arr,k):
    avg = []
    for i in range(len(arr)-k+1):
        nu = np.array(arr[i:i+k])
        avg.append(np.sum(nu)/k)
        avg_sequence = len(arr)-k+1
    print("moving average values : ",np.round_(avg,decimals=3)) 
    print("the moving average sequence has: ",avg_sequence)

arr = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k=3
print(movavg(arr,k))
    

moving average values :  [  5.      4.667   5.667   6.667   9.667  28.667  49.333  72.667  84.
  93.333 116.333]
the moving average sequence has:  11
None
